"""infra_usage and llm_daily tables

Revision ID: 32dd2cbeffe2
Revises: adb5e65f615b
Create Date: 2026-08-11 16:42:38.824673

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '32dd2cbeffe2'
down_revision: Union[str, Sequence[str], None] = 'adb5e65f615b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('infra_usage',
    sa.Column('period_start', sa.String(length=10), nullable=False),
    sa.Column('app', sa.String(length=64), nullable=False),
    sa.Column('capture_date', sa.String(length=10), nullable=False),
    sa.Column('cumulative_usd', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('period_start', 'app', 'capture_date')
    )
    op.create_table('llm_daily',
    sa.Column('date', sa.String(length=10), nullable=False),
    sa.Column('app', sa.String(length=64), nullable=False),
    sa.Column('model', sa.String(length=64), nullable=False),
    sa.Column('input_tokens', sa.Integer(), nullable=False),
    sa.Column('output_tokens', sa.Integer(), nullable=False),
    sa.Column('cache_read_tokens', sa.Integer(), nullable=False),
    sa.Column('cache_creation_tokens', sa.Integer(), nullable=False),
    sa.Column('cost_usd', sa.Float(), nullable=False),
    sa.Column('call_count', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('date', 'app', 'model')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('llm_daily')
    op.drop_table('infra_usage')
    # ### end Alembic commands ###
