"""phase5 app-owned tables

Revision ID: 334147163440
Revises: 578a2678f0fc
Create Date: 2026-08-11 20:55:11.819123

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '334147163440'
down_revision: Union[str, Sequence[str], None] = '578a2678f0fc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dismissals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('target', sa.String(length=120), nullable=False),
    sa.Column('reason', sa.String(length=500), nullable=False),
    sa.Column('created_at', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dismissals_kind'), 'dismissals', ['kind'], unique=False)
    op.create_index(op.f('ix_dismissals_target'), 'dismissals', ['target'], unique=False)
    op.create_table('feature_checkoffs',
    sa.Column('feature_name', sa.String(length=120), nullable=False),
    sa.Column('checked_at', sa.String(length=32), nullable=False),
    sa.Column('note', sa.String(length=500), nullable=False),
    sa.PrimaryKeyConstraint('feature_name')
    )
    op.create_table('goals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('target', sa.String(length=120), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('target_date', sa.String(length=10), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('notes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subject_kind', sa.String(length=16), nullable=False),
    sa.Column('subject_id', sa.String(length=120), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('created_at', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notes_subject_id'), 'notes', ['subject_id'], unique=False)
    op.create_index(op.f('ix_notes_subject_kind'), 'notes', ['subject_kind'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_notes_subject_kind'), table_name='notes')
    op.drop_index(op.f('ix_notes_subject_id'), table_name='notes')
    op.drop_table('notes')
    op.drop_table('goals')
    op.drop_table('feature_checkoffs')
    op.drop_index(op.f('ix_dismissals_target'), table_name='dismissals')
    op.drop_index(op.f('ix_dismissals_kind'), table_name='dismissals')
    op.drop_table('dismissals')
    # ### end Alembic commands ###
