"""briefs and watcher_state tables

Revision ID: 578a2678f0fc
Revises: e04ad81efc7d
Create Date: 2026-08-11 20:22:11.596140

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '578a2678f0fc'
down_revision: Union[str, Sequence[str], None] = 'e04ad81efc7d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('briefs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.String(length=32), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('model', sa.String(length=64), nullable=False),
    sa.Column('input_tokens', sa.Integer(), nullable=False),
    sa.Column('output_tokens', sa.Integer(), nullable=False),
    sa.Column('cost_usd', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('error', sa.String(length=500), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_briefs_created_at'), 'briefs', ['created_at'], unique=False)
    op.create_table('watcher_state',
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('value', sa.String(length=200), nullable=False),
    sa.Column('updated_at', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('watcher_state')
    op.drop_index(op.f('ix_briefs_created_at'), table_name='briefs')
    op.drop_table('briefs')
    # ### end Alembic commands ###
