"""infra_service_usage table

Revision ID: e04ad81efc7d
Revises: 32dd2cbeffe2
Create Date: 2026-08-11 19:54:25.601966

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e04ad81efc7d'
down_revision: Union[str, Sequence[str], None] = '32dd2cbeffe2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('infra_service_usage',
    sa.Column('period_start', sa.String(length=10), nullable=False),
    sa.Column('app', sa.String(length=64), nullable=False),
    sa.Column('service_id', sa.String(length=64), nullable=False),
    sa.Column('capture_date', sa.String(length=10), nullable=False),
    sa.Column('service_name', sa.String(length=120), nullable=False),
    sa.Column('cumulative_usd', sa.Float(), nullable=False),
    sa.Column('memory_usd', sa.Float(), nullable=False),
    sa.Column('cpu_usd', sa.Float(), nullable=False),
    sa.Column('egress_usd', sa.Float(), nullable=False),
    sa.Column('volume_usd', sa.Float(), nullable=False),
    sa.Column('backup_usd', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('period_start', 'app', 'service_id', 'capture_date')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('infra_service_usage')
    # ### end Alembic commands ###
