"""initial ingested tables

Revision ID: e6bdbc48ffd8
Revises: 
Create Date: 2026-08-02 21:47:40.617709

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e6bdbc48ffd8'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activity_daily',
    sa.Column('date', sa.String(length=10), nullable=False),
    sa.Column('commits', sa.Integer(), nullable=False),
    sa.Column('by_repo', sa.JSON(), nullable=False),
    sa.Column('sessions', sa.Integer(), nullable=True),
    sa.Column('prompts', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('date')
    )
    op.create_table('feature_catalog',
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('lesson', sa.String(length=60), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('discovered_at', sa.String(length=10), nullable=False),
    sa.PrimaryKeyConstraint('name')
    )
    op.create_table('feature_units',
    sa.Column('key', sa.String(length=32), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('repo', sa.String(length=200), nullable=False),
    sa.Column('date', sa.String(length=10), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('tags', sa.JSON(), nullable=False),
    sa.Column('complexity', sa.Integer(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('model', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_index(op.f('ix_feature_units_date'), 'feature_units', ['date'], unique=False)
    op.create_index(op.f('ix_feature_units_repo'), 'feature_units', ['repo'], unique=False)
    op.create_table('snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('captured_at', sa.String(length=40), nullable=False),
    sa.Column('sweep_stats', sa.JSON(), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_snapshots_content_hash'), 'snapshots', ['content_hash'], unique=True)
    op.create_table('adoption_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('snapshot_id', sa.Integer(), nullable=False),
    sa.Column('feature_name', sa.String(length=120), nullable=False),
    sa.Column('lesson', sa.String(length=60), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('last_used', sa.String(length=10), nullable=True),
    sa.ForeignKeyConstraint(['snapshot_id'], ['snapshots.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_adoption_history_feature_name'), 'adoption_history', ['feature_name'], unique=False)
    op.create_index(op.f('ix_adoption_history_snapshot_id'), 'adoption_history', ['snapshot_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_adoption_history_snapshot_id'), table_name='adoption_history')
    op.drop_index(op.f('ix_adoption_history_feature_name'), table_name='adoption_history')
    op.drop_table('adoption_history')
    op.drop_index(op.f('ix_snapshots_content_hash'), table_name='snapshots')
    op.drop_table('snapshots')
    op.drop_index(op.f('ix_feature_units_repo'), table_name='feature_units')
    op.drop_index(op.f('ix_feature_units_date'), table_name='feature_units')
    op.drop_table('feature_units')
    op.drop_table('feature_catalog')
    op.drop_table('activity_daily')
    # ### end Alembic commands ###
